name: clang-format

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*.md'

jobs:
  formatting-check:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install clang-format
      run: |
        pip install clang-format \
        && clang-format --version
      shell: bash

    - name: Format files
      run: ${{github.workspace}}/scripts/format.sh ${{github.workspace}} y
      shell: bash

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: ':octocat: Applied clang-format. [skip build]'
        add: '["*.cxx", "*.hxx", "*.hip"]' # Update this with extensions you use in your project.
